// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.damon.protobuf.addressbook;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:app.AddressBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person> 
        getPersonList();
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    com.damon.protobuf.addressbook.PersonProtos.Person getPerson(int index);
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    java.util.List<? extends com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code app.AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:app.AddressBook)
      AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<com.damon.protobuf.addressbook.PersonProtos.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(com.damon.protobuf.addressbook.PersonProtos.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damon.protobuf.addressbook.AddressBookProtos.internal_static_app_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damon.protobuf.addressbook.AddressBookProtos.internal_static_app_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.class, com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person> person_;
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    public java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    public java.util.List<? extends com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    public com.damon.protobuf.addressbook.PersonProtos.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .app.Person person = 1;</code>
     */
    public com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damon.protobuf.addressbook.AddressBookProtos.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:app.AddressBook)
        com.damon.protobuf.addressbook.AddressBookProtos.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damon.protobuf.addressbook.AddressBookProtos.internal_static_app_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damon.protobuf.addressbook.AddressBookProtos.internal_static_app_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.class, com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.Builder.class);
      }

      // Construct using com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damon.protobuf.addressbook.AddressBookProtos.internal_static_app_AddressBook_descriptor;
      }

      public com.damon.protobuf.addressbook.AddressBookProtos.AddressBook getDefaultInstanceForType() {
        return com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance();
      }

      public com.damon.protobuf.addressbook.AddressBookProtos.AddressBook build() {
        com.damon.protobuf.addressbook.AddressBookProtos.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.damon.protobuf.addressbook.AddressBookProtos.AddressBook buildPartial() {
        com.damon.protobuf.addressbook.AddressBookProtos.AddressBook result = new com.damon.protobuf.addressbook.AddressBookProtos.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damon.protobuf.addressbook.AddressBookProtos.AddressBook) {
          return mergeFrom((com.damon.protobuf.addressbook.AddressBookProtos.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.damon.protobuf.addressbook.AddressBookProtos.AddressBook other) {
        if (other == com.damon.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.damon.protobuf.addressbook.AddressBookProtos.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.damon.protobuf.addressbook.AddressBookProtos.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<com.damon.protobuf.addressbook.PersonProtos.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.damon.protobuf.addressbook.PersonProtos.Person, com.damon.protobuf.addressbook.PersonProtos.Person.Builder, com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public com.damon.protobuf.addressbook.PersonProtos.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.damon.protobuf.addressbook.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.damon.protobuf.addressbook.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder addPerson(com.damon.protobuf.addressbook.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.damon.protobuf.addressbook.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder addPerson(
          com.damon.protobuf.addressbook.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.damon.protobuf.addressbook.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.damon.protobuf.addressbook.PersonProtos.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public com.damon.protobuf.addressbook.PersonProtos.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public java.util.List<? extends com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public com.damon.protobuf.addressbook.PersonProtos.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            com.damon.protobuf.addressbook.PersonProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public com.damon.protobuf.addressbook.PersonProtos.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, com.damon.protobuf.addressbook.PersonProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .app.Person person = 1;</code>
       */
      public java.util.List<com.damon.protobuf.addressbook.PersonProtos.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damon.protobuf.addressbook.PersonProtos.Person, com.damon.protobuf.addressbook.PersonProtos.Person.Builder, com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.damon.protobuf.addressbook.PersonProtos.Person, com.damon.protobuf.addressbook.PersonProtos.Person.Builder, com.damon.protobuf.addressbook.PersonProtos.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:app.AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:app.AddressBook)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_app_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\003app\032\014person.proto\"*" +
      "\n\013AddressBook\022\033\n\006person\030\001 \003(\0132\013.app.Pers" +
      "onB3\n\036com.damon.protobuf.addressbookB\021Ad" +
      "dressBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.damon.protobuf.addressbook.PersonProtos.getDescriptor(),
        }, assigner);
    internal_static_app_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_app_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_app_AddressBook_descriptor,
        new java.lang.String[] { "Person", });
    com.damon.protobuf.addressbook.PersonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
